@description Flat Madness Black
@version 4.0.2
@changelog
    Fixed bug of wrong view when FX was disabled in TCP
@provides Flat Madness Black.ReaperThemeZip
@author Dmytro Hapochka
@donation https://buymeacoffee.com/flatmadness
@link Forum Thread https://forum.cockos.com/showthread.php?t=247086
@screenshot https://github.com/gapalil001/FlatMadness/raw/master/Adjuster/images/screenshot.png
@about
    Hi Everyone! this theme is created for people who love modern cute flat design. This theme is created to make people enjoy to work with TCP FX list, so at first - go to options, and enable "show FX inserts in TCP" and "show FX sends in TCP" enjoy!