@description Flat Madness Bright
@version 3.8
@changelog
 - new TCP behavior when FX or send lists are not visible
 - longname 2 layout removed
 - longname layout is fixed and fit new logic
 - little design changes
@provides Flat Madness Bright.ReaperThemeZip
@author Dmytro Hapochka
@links
  Forum Thread https://forum.cockos.com/showthread.php?t=247086
@screenshots
  Overview https://stash.reaper.fm/44544/FM171D.png
@about
  description