@description Flat Madness Dark
@version 3.71
@changelog
  - TCP solid color layout changed again.
  - some panels and buttons in dark versions are becoming darker. fixed issue with “bright meter” on “sidemeter” adjuster positions
@provides Flat Madness Dark.ReaperThemeZip
@author Dmytry Hapochka
@links
  Forum Thread https://forum.cockos.com/showthread.php?t=247086
@screenshots
  Overview https://stash.reaper.fm/44544/FM171D.png
@about
  description